TestCRUD/Models/ErrorViewModel.cs
using System;

namespace TestCRUD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestCRUD/Models/StudentModel.cs
namespace TestCRUD.Models
{
    public class StudentModel
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public string University { get; set; }
        public string City { get; set; }
    }
}

TestCRUD/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TestCRUD.Models;

namespace TestCRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestCRUD/Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestCRUD.Data;
using TestCRUD.Models;

namespace TestCRUD.Controllers
{
    public class TableController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TableController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable <StudentModel> students = _context.Students;
            return View(students);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StudentModel student)
        {
            _context.Students.Add(student);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int? id)
        {
            var student = _context.Students.Find(id);
            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(StudentModel studentEdit)
        {
            _context.Students.Update(studentEdit);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int? id)
        {
            var student = _context.Students.Find(id);
            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(StudentModel studentEdit)
        {
            _context.Students.Remove(studentEdit);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

TestCRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TestCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestCRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Table" asp-action="Index">Table</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TestCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TestCRUD/Views/Table/Create.cshtml
@model StudentModel


<form method="post" asp-action="Create">
    <div class="form-control">
        <label>Student Name</label>
        <input asp-for="StudentName" placeholder="Name"/>
    </div>
    <div class="form-control">
        <label>University</label>
        <input asp-for="University" placeholder="School"/>
    </div>
    <div class="form-control">
        <label>City</label>
        <input asp-for="City" placeholder="eg. Auckland"/>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

TestCRUD/Views/Table/Delete.cshtml
@model StudentModel

<h2>Are you sure you want to delete?</h2>
<div>
    <label>Name: @Model.StudentName</label>
    <label>Uni: @Model.University</label>
    <label>City: @Model.City</label>
    <form method="post" asp-action="Delete">
        <button class="btn btn-danger text-white" type="submit">Delete</button>
        <button class="btn btn-light text-black" asp-action="Index">Cancel</button>
    </form>
</div>

TestCRUD/Views/Table/Edit.cshtml
@model StudentModel


<form method="post" asp-action="Edit">
    <div class="form-control">
        <label>Student Name</label>
        <input asp-for="StudentName" placeholder="Name" />
    </div>
    <div class="form-control">
        <label>University</label>
        <input asp-for="University" placeholder="School" />
    </div>
    <div class="form-control">
        <label>City</label>
        <input asp-for="City" placeholder="eg. Auckland" />
    </div>
    <button type="submit" class="btn btn-primary">Edit</button>
</form>

TestCRUD/Views/Table/Index.cshtml
@model IEnumerable<StudentModel>;

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Student Name</th>
            <th>University</th>
            <th>City</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model)
        {
            <tr>
                <td>@i.StudentName</td>
                <td>@i.University</td>
                <td>@i.City</td>
                <td><a class="btn btn-primary text-white text-center" asp-area="" asp-controller="Table" asp-action="Edit" asp-route-Id="@i.Id">Edit</a></td>
                <td><a class="btn btn-danger text-white text-center" asp-area="" asp-controller="Table" asp-action="Delete" asp-route-Id="@i.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a class="btn btn-primary" asp-area="" asp-controller="Table" asp-action="Create">Create</a>
</div>